[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.1.0"
langchain-openai = "^0.0.2"
langchain-community = "^0.0.10"
openai = "^1.3.0"
python-dotenv = "^1.0.0"
chromadb = "^0.4.22"
sentence-transformers = "^2.2.2" 